<?php

    $lastOrderId = $block->getOrderDetails();
    $customerEmail = $block->getCustomerEmail($lastOrderId);
    $guestCustomer = $block->getGuestCustomer($customerEmail);
    $writer = new \Zend\Log\Writer\Stream(BP . '/var/log/ORDERSUCCESSS.log');
    $logger = new \Zend\Log\Logger();
    $logger->addWriter($writer);
    $logger->info('lAT ORDER ID'.$lastOrderId);
    $logger->info('cUSTOMER EMAIL'.$customerEmail);
    $logger->info('cUSTOMER ID'.$guestCustomer);
?>

<div class="checkout-success">
    <?php if (empty($guestCustomer)): ?>
        <p>Your order # is: <span><?php echo $lastOrderId ?></span>.</p>
    <?php else: ?>
        <p>Your order number is: <a href="<?php echo $block->getBaseUrl();?>/sales/order/view/order_id/<?php echo $lastOrderId ?>/" class="order-number"><strong><?php echo $lastOrderId ?></strong></a>.</p>
    <?php endif; ?>
    <p>We'll email you an order confirmation with details and tracking info.</p>
    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= $block->escapeUrl($block->getBaseUrl()) ?>"><span><?= $block->escapeHtml(__('Continue Shopping')) ?></span></a>
        </div>
    </div>

<div>
<?php if (empty($guestCustomer)): ?>
    <div id="registration">
        <br>
        <div>
            <p><?= $block->escapeHtml(__('You can track your order status by creating an account.')) ?></p>
            <p><span><?= $block->escapeHtml(__('Email Address')) ?></span>: <span><?php echo $customerEmail;?></span></p>
            <a class="action primary"  href="<?php echo $block->getBaseUrl();?>/create/account/">>
                <span><?= $block->escapeHtml(__('Create an Account')) ?></span>
            </a>
        </div>
    </div>
<?php endif; ?>



