<!-- <h2>Shello...</h2> -->
<style>
    .custom-button
    {
        background-image: none;
        background: #FE9B30;
        border: 1px solid #FE9B30;
        color: #fff;
        cursor: pointer;
        display: inline-block;
        font-family: 'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;
        font-weight: 600;
        box-sizing: border-box;
        vertical-align: middle;
        float: left;
        line-height: 2.2rem;
        padding: 14px 17px;
        font-size: 1.8rem;
        margin-bottom: 15px;
        width: 20%;
        border-radius: 3px;
    }
    .action,.primary
    {
        float: left;
    }
</style>
<a href ="<?php echo $block->getBaseUrl();?>"><input class="custom-button" type="button" value="Continue Shopping" />  </a>
